name: doubledescent
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - dill
  - pandas
  - seaborn
  - scipy
  - jupyterlab
  - pip
  - ipdb
  - cython
  - pyarrow >= 2
  - scikit-learn
  - tqdm
  - pytorch
  - torchvision
  - opencv
  - ipywidgets
  - black
  - isort